FROM node:16-alpine

WORKDIR /app

COPY ./front .

RUN npm install -g npm@8.18.0

RUN npm install

# create user and make him owner of the WORKDIR directory
RUN adduser -D usersvelte
RUN chown -R usersvelte:usersvelte  /app
USER usersvelte

CMD [ "npm", "run" , "dev"]